# Generated by Django 6.0 on 2025-12-13 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="account",
            name="bucket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="accounts",
                to="finance.bucket",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="accounts",
                to="finance.accountcategory",
            ),
        ),
        migrations.AlterField(
            model_name="accountcategory",
            name="account_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="finance.accounttype",
            ),
        ),
        migrations.AlterField(
            model_name="accounttype",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="bucket",
            name="name",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="finance.account",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="note",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name="accountcategory",
            unique_together={("name", "account_type")},
        ),
        migrations.AddField(
            model_name="account",
            name="portfolio",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts",
                to="finance.portfolio",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="account",
            unique_together={("portfolio", "name")},
        ),
    ]
