# Generated by Django 6.0 on 2025-12-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_alter_transaction_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactioncategory",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name="transactioncategory",
            unique_together={("portfolio", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="transactionsubcategory",
            unique_together={("portfolio", "category", "name")},
        ),
    ]
