# Generated by Django 6.0 on 2026-01-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_alter_transactioncategory_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="subcategory",
        ),
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ["-date"]},
        ),
        migrations.AlterModelOptions(
            name="transactioncategory",
            options={
                "ordering": ["type", "name"],
                "verbose_name_plural": "Transaction Categories",
            },
        ),
        migrations.AlterUniqueTogether(
            name="transactioncategory",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="transactioncategory",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transactioncategory",
            name="type",
            field=models.CharField(
                choices=[
                    ("Income", "Income"),
                    ("Expense", "Expense"),
                    ("Transfer", "Transfer"),
                ],
                default="Debit",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[("Credit", "Credit"), ("Debit", "Debit")], max_length=10
            ),
        ),
        migrations.AlterUniqueTogether(
            name="transactioncategory",
            unique_together={("portfolio", "name", "type")},
        ),
        migrations.DeleteModel(
            name="TransactionSubcategory",
        ),
    ]
