# Generated by Django 6.0 on 2025-12-13 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_portfolio_owner_userprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="portfolio",
            name="owner",
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
