# Generated by Django 6.0 on 2025-12-13 14:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0004_remove_portfolio_owner_delete_userprofile"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="accountcategory",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="accountcategory",
            name="portfolio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account_categories",
                to="finance.portfolio",
            ),
        ),
        migrations.AddField(
            model_name="accounttype",
            name="portfolio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account_types",
                to="finance.portfolio",
            ),
        ),
        migrations.AddField(
            model_name="bucket",
            name="portfolio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buckets",
                to="finance.portfolio",
            ),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="user",
            field=models.CharField(default="demo_user", max_length=100),
        ),
        migrations.AlterField(
            model_name="account",
            name="portfolio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts",
                to="finance.portfolio",
            ),
        ),
        migrations.AlterField(
            model_name="accounttype",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="bucket",
            name="name",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name="accountcategory",
            unique_together={("portfolio", "account_type", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="accounttype",
            unique_together={("portfolio", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="bucket",
            unique_together={("portfolio", "name")},
        ),
    ]
