# Generated by Django 6.0 on 2025-12-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0005_alter_accountcategory_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
