# Generated by Django 6.0 on 2025-12-15 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0006_portfolio_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Transaction Categories",
            },
        ),
        migrations.CreateModel(
            name="BalanceSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("balance", models.DecimalField(decimal_places=2, max_digits=12)),
                ("snapshot_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balance_snapshots",
                        to="finance.account",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="transaction",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="finance.transactioncategory",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="TransactionSubcategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="finance.transactioncategory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Transaction Subcategories",
            },
        ),
        migrations.AddField(
            model_name="transaction",
            name="subcategory",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="finance.transactionsubcategory",
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["account", "date"], name="finance_tra_account_588697_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["date", "category"], name="finance_tra_date_13523c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="balancesnapshot",
            index=models.Index(
                fields=["account", "snapshot_date"],
                name="finance_bal_account_c25891_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="balancesnapshot",
            index=models.Index(
                fields=["snapshot_date"], name="finance_bal_snapsho_a79515_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="balancesnapshot",
            unique_together={("account", "snapshot_date")},
        ),
        migrations.AlterUniqueTogether(
            name="transactionsubcategory",
            unique_together={("category", "name")},
        ),
    ]
