# Generated by Django 6.0 on 2025-12-15 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0007_transactioncategory_balancesnapshot_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="bucket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts",
                to="finance.bucket",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts",
                to="finance.accountcategory",
            ),
        ),
    ]
